// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Roborally
Roborally Game server


    Schemes:
      http
    Host: localhost
    BasePath: /api
    Version: 0.0.1
    License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
    Contact: <wim.ockerman@telenet.be>

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
