// Code generated by go-swagger; DO NOT EDIT.

package main

import (
	"fmt"
	"log"
	"os"

	loads "github.com/go-openapi/loads"
	flag "github.com/spf13/pflag"

	"ockernuts/goroborally/restapi"
	"ockernuts/goroborally/restapi/operations"
)

// This file was generated by the swagger tool.
// Make sure not to overwrite this file after you generated it because all your edits would be lost!

func main() {
	log.Println("Starting Roborally-server")
	cwd, err := os.Getwd()
	if err != nil {
		log.Panicf("Cannot get current working dir. Error: %v", err)
	}
	log.Println("Current working directory:", cwd)

	swaggerSpec, err := loads.Analyzed(restapi.SwaggerJSON, "")
	if err != nil {
		log.Fatalln(err)
	}

	var server *restapi.Server // make sure init is called

	flag.Usage = func() {
		fmt.Fprint(os.Stderr, "Usage:\n")
		fmt.Fprint(os.Stderr, "  roborally-server [OPTIONS]\n\n")

		title := "Roborally"
		fmt.Fprint(os.Stderr, title+"\n\n")
		desc := "Roborally Game server"
		if desc != "" {
			fmt.Fprintf(os.Stderr, desc+"\n\n")
		}
		fmt.Fprintln(os.Stderr, flag.CommandLine.FlagUsages())
	}
	// parse the CLI flags
	flag.Parse()

	api := operations.NewRoborallyAPI(swaggerSpec)
	// get server with flag values filled out
	server = restapi.NewServer(api)

	defer server.Shutdown()

	server.ConfigureAPI()
	if err := server.Serve(); err != nil {
		log.Fatalln(err)
	}

}
