// Code generated by go-swagger; DO NOT EDIT.

package board

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetBoardByNameHandlerFunc turns a function with the right signature into a get board by name handler
type GetBoardByNameHandlerFunc func(GetBoardByNameParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetBoardByNameHandlerFunc) Handle(params GetBoardByNameParams) middleware.Responder {
	return fn(params)
}

// GetBoardByNameHandler interface for that can handle valid get board by name params
type GetBoardByNameHandler interface {
	Handle(GetBoardByNameParams) middleware.Responder
}

// NewGetBoardByName creates a new http.Handler for the get board by name operation
func NewGetBoardByName(ctx *middleware.Context, handler GetBoardByNameHandler) *GetBoardByName {
	return &GetBoardByName{Context: ctx, Handler: handler}
}

/*GetBoardByName swagger:route GET /v1/boards/{name} Board getBoardByName

Retrieve detailed info of available boards on the server

*/
type GetBoardByName struct {
	Context *middleware.Context
	Handler GetBoardByNameHandler
}

func (o *GetBoardByName) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetBoardByNameParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
