// Code generated by go-swagger; DO NOT EDIT.

package board

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetBoardsHandlerFunc turns a function with the right signature into a get boards handler
type GetBoardsHandlerFunc func(GetBoardsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetBoardsHandlerFunc) Handle(params GetBoardsParams) middleware.Responder {
	return fn(params)
}

// GetBoardsHandler interface for that can handle valid get boards params
type GetBoardsHandler interface {
	Handle(GetBoardsParams) middleware.Responder
}

// NewGetBoards creates a new http.Handler for the get boards operation
func NewGetBoards(ctx *middleware.Context, handler GetBoardsHandler) *GetBoards {
	return &GetBoards{Context: ctx, Handler: handler}
}

/*GetBoards swagger:route GET /v1/boards Board getBoards

Retrieve basic info of boards availble on the server

*/
type GetBoards struct {
	Context *middleware.Context
	Handler GetBoardsHandler
}

func (o *GetBoards) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetBoardsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
