// Code generated by go-swagger; DO NOT EDIT.

package board

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"ockernuts/goroborally/models"
)

// GetBoardsOKCode is the HTTP code returned for type GetBoardsOK
const GetBoardsOKCode int = 200

/*GetBoardsOK boards response

swagger:response getBoardsOK
*/
type GetBoardsOK struct {

	/*
	  In: Body
	*/
	Payload []string `json:"body,omitempty"`
}

// NewGetBoardsOK creates GetBoardsOK with default headers values
func NewGetBoardsOK() *GetBoardsOK {
	return &GetBoardsOK{}
}

// WithPayload adds the payload to the get boards o k response
func (o *GetBoardsOK) WithPayload(payload []string) *GetBoardsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get boards o k response
func (o *GetBoardsOK) SetPayload(payload []string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBoardsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]string, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetBoardsDefault for errors 500 in case of bad board provider setup

swagger:response getBoardsDefault
*/
type GetBoardsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBoardsDefault creates GetBoardsDefault with default headers values
func NewGetBoardsDefault(code int) *GetBoardsDefault {
	if code <= 0 {
		code = 500
	}

	return &GetBoardsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get boards default response
func (o *GetBoardsDefault) WithStatusCode(code int) *GetBoardsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get boards default response
func (o *GetBoardsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get boards default response
func (o *GetBoardsDefault) WithPayload(payload *models.Error) *GetBoardsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get boards default response
func (o *GetBoardsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBoardsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
