// Code generated by go-swagger; DO NOT EDIT.

package board

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"ockernuts/goroborally/models"
)

// GetBoardByNameOKCode is the HTTP code returned for type GetBoardByNameOK
const GetBoardByNameOKCode int = 200

/*GetBoardByNameOK boards response

swagger:response getBoardByNameOK
*/
type GetBoardByNameOK struct {

	/*
	  In: Body
	*/
	Payload *models.Board `json:"body,omitempty"`
}

// NewGetBoardByNameOK creates GetBoardByNameOK with default headers values
func NewGetBoardByNameOK() *GetBoardByNameOK {
	return &GetBoardByNameOK{}
}

// WithPayload adds the payload to the get board by name o k response
func (o *GetBoardByNameOK) WithPayload(payload *models.Board) *GetBoardByNameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get board by name o k response
func (o *GetBoardByNameOK) SetPayload(payload *models.Board) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBoardByNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetBoardByNameDefault for errors 404 and 500

swagger:response getBoardByNameDefault
*/
type GetBoardByNameDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBoardByNameDefault creates GetBoardByNameDefault with default headers values
func NewGetBoardByNameDefault(code int) *GetBoardByNameDefault {
	if code <= 0 {
		code = 500
	}

	return &GetBoardByNameDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get board by name default response
func (o *GetBoardByNameDefault) WithStatusCode(code int) *GetBoardByNameDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get board by name default response
func (o *GetBoardByNameDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get board by name default response
func (o *GetBoardByNameDefault) WithPayload(payload *models.Error) *GetBoardByNameDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get board by name default response
func (o *GetBoardByNameDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBoardByNameDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
